agent:
    __init__:
        batch_size: 10
        samples_per_insert: 2
        min_replay_size: 10
    evaluate:
        num_episodes: 100
    learn:
        num_episodes: 100
network:
    __init__:
        foo: 100
environment:
    __init__:
        bar: 200
__global__:
    backing_dir: "./.aos/data"
    discount: .99
